site_name: Internal Solutions Template
site_description: Documentation for the Internal Solutions Template project
site_author: NXT Humans

# Repository
repo_name: nxt-humans/internal-solutions-template
repo_url: https://github.com/nxt-humans/internal-solutions-template

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

# Plugins
plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

# Navigation
nav:
  - Home: index.md
  - Setup: setup.md
  - Deployment: deployment.md
  - Guides:
    - Architecture: guides/architecture.md
    - FastAPI Backend: guides/fastapi.md
    - React Frontend: guides/react.md
    - Python Development: guides/python.md
    - Docker Optimization: guides/optimized-dockerfiles.md
    - Internal Solutions: guides/internal-solutions.md

# Development server
dev_addr: '0.0.0.0:8000'